### ISSUE TITLE
Unusable since 1.12.5

### ISSUE THREAD

**Issue by spikehidden** [nikosgram/gringotts-towny#10]
Towny does not retrieve the correct amount a town owns from Gringotts.

Ex: 5000 Coins are in the vault of the town Berlin
If you do any Towny action that requires the town to have money it gets blocked and says it would be bankrupt. But when I run `/mad balance town:Berlin` it outputs the correct amount.

Same goes for `/town Berlin` which shows `Bank: 0` in their stats.

<details>
<summary>Plugins</summary>

#### Paper Plugins: (2):
- BKCommonLib
- EconomyShopGUI-Premium
#### Bukkit Plugins: (67):
- AppleCoreSpigot
- Chunky
- Citizens
- CitizensGUI
- ClientDetector
- CrossplatForms
- dDiscordBot
- Denizen
- Depenizen
- DiscordSRV
- DropEdit2
- dynmap
- Dynmap-Towny
- Dynmap-WorldGuard
- Essentials
- EssentialsChat
- EssentialsGeoIP
- EssentialsSpawn
- ExtraContexts
- FallingSnow
- floodgate
- GeyserHacks
- Gringotts
- GringottsTowny
- ImageFrame
- InteractionVisualizer
- InteractiveChat
- InteractiveChatDiscordSrvAddon
- JShader
- LuckPerms
- MultiLang
- Multiverse-Core
- Multiverse-NetherPortals
- Multiverse-Portals
- Multiverse-SignPortals
- NBTAPI
- Pl-Hide-Pro
- PlaceholderAPI
- PowerBoard
- ProtocolLib
- PurpurExtras
- qsaddon-discordsrv
- qsaddon-discount
- qsaddon-displaycontrol
- qscompat-towny
- qscompat-worldedit
- qscompat-worldguard
- qssuite-limited
- QuickShop-Hikari
- RocketPlaceholders
- SiegeWar
- spark
- StreamingDrops
- TCHangRail
- Themis
- Towny
- TownyCamps
- TownyCaptureSites
- TownyHistories
- TownyMenus
- TownyResources
- TownyWayPointTravel
- Train_Carts
- Vault
- WorldEdit
- WorldGuard
- WorldGuard-Towny

</details>

<details>
<summary>/plugins/Gringotts/config.yml</summary>

```yaml
# for details on configuration, see https://github.com/MinecraftWars/Gringotts/blob/master/doc/configuration.md

# supported languages: "custom" (default, english), "de" (german), "fr" (french), and "pt-BR" (brazilian portuguese).
language: de

# regex that create a vault if matches with a sign
# subpattern 1 denotes the type of the vault.
vault_pattern: '[^\[]*\[(\w*) ?vault\]'

# If this is set to true, when the user receives an amount of money
# exceeding the inventory capacity, drop items that didn't fit.
drop-overflowing-item: false

# currency name and value config
currency:
  # currency name to use in messages
  name:
    singular: Fuchstaler
    plural: Fuchstaler

  # number of decimal digits supported by currency value (0 for whole numbers only)
  digits: 2

  # Display account balances with individual denomination names
  named-denominations: true

  # value of individual denominations. default: emerald: 1, emerald block: 9
  denominations:
    - material: iron_nugget
      value: 1
      unit-name: "&f&r"
      unit-name-plural: "&f&r"
      displayname: "&r&7&lEiserner Fuchstaler"
      damage: 13
      custom_model_data: 10
      lore:
        - "&f&lWert: &7&l1 Fuchstaler"
        - "&c&lNICHT CRAFTEN"
    - material: gold_nugget
      value: 100
      unit-name: "&f&r"
      unit-name-plural: "&f&r"
      displayname: "&r&l&6Golderner Fuchstaler"
      damage: 4
      custom_model_data: 10
      lore:
        - "&f&lWert: &7&l100 Fuchstaler"
        - "&c&lNICHT CRAFTEN"
    - material: emerald
      value: 1000
      unit-name: "&f&r"
      unit-name-plural: "&f&r"
      displayname: "&r&l&2Grüner Fuchstaler"
      damage: 11
      custom_model_data: 10
      lore:
        - "&f&lWert: &7&l1000 Fuchstaler"
        - "&c&lNICHT CRAFTEN"
    - material: copper_ingot
      value: 0.01
      unit-name: "&f&r"
      unit-name-plural: "&f&r"
      displayname: "&r&l&cKupferner Fuchstaler"
      damage: 11
      custom_model_data: 10
      lore:
        - "&f&lWert: &7&l0,01 Fuchstaler"
        - "&c&lNICHT CRAFTEN"

# tax on /money pay transactions
transactiontax:
  flat: 0.0
  rate: 0.0

# balance to start an account with (purely virtual)
startingbalance:
  player: 500

# globally (dis)allow use of vault types
usevault:
  container: true
  enderchest: true
  # if true, denomination items located in shulker boxes, in the above enabled inventories, will be included to the denomination finding process
  include-shulker-boxes: true

# whether money/balance commands show vault and inventory balance separately
balance:
  show-vault: true
  show-inventory: true
  show-enderchest: true
```
</details>

<details>
<summary>/plugins/GringottsTowny/config.yml</summary>

```yaml
# supported languages: "custom" (default, english), "de" (german), "fr" (french), and "pt-BR" (brazilian portuguese).
language: de

# changes the required sign name for the creation of town/nation vaults
# Example: [town vault]
town_sign_vault_name: 'town'
nation_sign_vault_name: 'nation'

# Prevents players from creating a vault outside a town if set to true
vaults_only_in_towns: false

# Maximum number of vaults a town can own, set to -1 for infinite number of vaults
max_town_vaults: -1
# Maximum number of vaults a nation can own, set to -1 for infinite number of vaults
max_nation_vaults: -1

# balance to start an account with (purely virtual)
town_start_balance: 1500
nation_start_balance: 15000
```

</details>
<details>
<summary>NOTE</summary>

> I am currently using 1.12.4 together with gringotts 1.12.5 because of this issue. Which also forced me to enable the legacy plugin loading order or GringottsTowny would be disabled.
> 
> Using 1.12.5 is also not perfect as described here:
> - nikosgram/gringotts#161

</details>
